### PR TITLE
feature: add brands sections

### PR DESCRIPTION
**Pull request by sivareddyuppathi**

### CODE REVIEW

**Comment by rahul-vashishtha** [comment]
@sivareddyuppathi Can you provide an explanation about the speciality of this component?

The thing is, what I can see is only a component with logos, and one component with Logo Marquee. Am I missing something?

**Comment by sivareddyuppathi** [comment]
Hi @rahul-vashishtha , Yeah you're right, but i can see this as more usefull component. because in many aplications they are using to show the Sponcers in their website.

Insted of doing the changes for Marquee. I thought like if we have specific component it will be more usefull to copy & paste.

**Comment by rahul-vashishtha** [comment]
@sivareddyuppathi 

Okay, got your point. This will be in the category of pre-made sections. For now, I'll approve this PR and merge it. Once I'll share the sections, we can move it to sections.

**Review by rahul-vashishtha — COMMENTED** [review]
Approved.

**Pull request merged**
