### PR TITLE
feat: add rainbow button

### PR DESCRIPTION
**Pull request by Grzechu335**

### CODE REVIEW

**Comment by nathan-de-pachtere** [comment]
Amazing !  

@Grzechu335 Can you make it not `button` only ? Using native component :is="" https://vuejs.org/guide/essentials/component-basics#dynamic-components

**Comment by Grzechu335** [comment]
@nathan-de-pachtere done!

**Review by rahul-vashishtha — CHANGES_REQUESTED** [review]
Fix the lint warning. using `pnpm lint:fix`

**Comment by Grzechu335** [comment]
@rahul-vashishtha I fixed linter warnings

**Review by rahul-vashishtha — APPROVED** [review]

**Review by rahul-vashishtha — APPROVED** [review]

**Pull request merged**
